### ISSUE TITLE
Slow performance of view service

### ISSUE THREAD

**Issue by amoeba** [NCEAS/metacat#1234]
We've seen some slow performance of the View Service for some time. Slow, meaning that it takes at least a few seconds, as bad as >10 seconds to return. I don't readily have an example of a very slow response but I did run the view service on a few recent documents on DataONE. I checked two EML 2.11 docs and one ISO-NOAA doc. I timed them using Firefox's network tab, Xalan 2.7.2, and xmlstarlet. I tested using both the metadataui.xsl and the metadata schema specific XSLs (e.g., isoroot.xsl, emlroot.xsl). For some reason, emlroot.xsl can't be run directly so those examples weren't run.

Overall, the network requests take 3-5 seconds. Xalan takes ~1s. Then when I run xmlstarlet, it's even faster, ~0.10s.

Key:

- **web:** I took the time from Firefox network panel
- **xalan-metacatui.xsl:** I ran `time java -jar xalan.jar {metadata.xml} metacatui.xsl`
- **xalan-isoroot.xsl:** I ran `time java -jar xalan.jar {metadata.xml}  isoroot.xsl`
- **xmlstarlet-metacatui:** I ran `time xmlstarlet tr metacatui.xsl {metadata.xml}`
- **xmlstarlet-isroot:** I ran `time xmlstarlet tr isoroot {metadata.xml}`

Results:

- https://search.dataone.org/#view/fridley.14.2

| method | result|
|-|-|
|web |`3339 ms`|
|xalan |`1.27 real         3.28 user         0.20 sys`|
|xmlstarlet-metacatui:| `0.15 real         0.08 user         0.01 sys`|

- https://search.dataone.org/#view/urn:uuid:0b35cf97-fa3a-475c-b2f2-530236e05f1e

| method | result|
|-|-|
web| `3393 ms`|
xalan |`1.26 real         3.34 user         0.22 sys`|
xmlstartlet-metacatui.xsl: |`0.16 real         0.07 user         0.01 sys`|

- https://search.dataone.org/#view/{850F24D4-5541-449F-80F6-F39E3DBA1FDD}

| method | result|
|-|-|
|web `4361 ms`
|xalan-metacatui.xsl |`1.04 real         2.53 user         0.18 sys`|
|xalan-isoroot.xsl| `0.65 real         0.97 user         0.10 sys`|
|xmlstarlet-metacatui |`0.15 real         0.07 user         0.01 sys`|
|xmlstarlet-isoroot |`0.05 real         0.01 user         0.00 sys`|

Interpretation/Questions:

It really looks like either the JVM or Xalan is the culprit here. Since I'm running this via the `java` executable, I bet a large portion of that time is JVM startup so it'd be good to benchmark this with a warmed up JVM instead of how I'm doing it.

- It doesn't look like metacatui.xsl is a slow part here because the wall time for xmlstarlet-metacatui and xmlstarlet-isoroot is essentially the same. This makes intuitive sense to me
- Can we flamegraph the web request on the server side to see where the slow parts are? I haven't profiled Metacat and Java applications so I'm not sure how easy this is
- If Xalan is slow, can we swap this out with a faster XSLT processor?

**Comment by csjx** [comment]
I happened to look at the `DBTransform` code when the UXL report came in from Rachel.  The first noticeable issue is that we immediately turn the XML document to be transformed into a `String`, rather than just passing the `InputStream` along to eventually be used in the `transform()` call.  Also, 
Jing @taojing2002 had added a method called `removeDOCTYPE()` that stripped the declaration out of the string to address an issue with incorrect system id values.  This wasn't well documented in the code or in subversion, so I don't know what ticket it belongs to or what it resolves.  But nonetheless, I would say we shouldn't be converting to a string and manipulating it.  I think creating a `StreamSource` using the `InputStream` version of the constructor might help with performance, and to possibly see if the Xalan implementation has a configuration to ignore stated system id values.
Also, in `DBTransform.getStyleSystemId()`, which calls `getPathContent()`we create a DOM document from the XSL to look up the stylesheets based on the `qformat` parameter. I don't fully follow the code after skimming it, but spinning up a DOM seems like a lot of overhead, and perhaps we could look at alternatives.
Third, we might look into caching `DBTransform` instance and re-using a pool of them since we instantiate a new one for every `view()` call - that might gain us a bit.
Last, I've read that slow transform times can be attributed to very long Java classpath values, and the `TransformerFactory` needs to search the whole classpath for transformer implementations.  Apparently you can pass the exact class you want to use in via a Java system parameter so there's no lookup involved during transformer instantiation.

Food for thought.

**Comment by amoeba** [comment]
That's a feast for thought, thanks @csjx !

**Comment by csjx** [comment]
We're seeing this issue on the CNs, and Dave has done some profiling of the `View` service: https://cn-unm-1.dataone.org/profiling/view_object.svg.  One thing to look at is the SSL processing during the transformation process.  There shouldn't be an SSL connection when getting the XSL stylesheet for the `metacatui` skin. But we see SSL calls in the profile stack. Let's track those down, it might provide some insight.

**Comment by amoeba** [comment]
Also worth noting is that different browsers end up showing different timings for the request so I think some part of my "benchmarks" above were bogus: For a request to https://search.dataone.org/cn/v2/views/metacatui/fridley.14.2, Chrome does it in 2.18s, Firefox 837ms, Safari 1.11s. For each browser, 90+% of the time is just waiting for the first byte.

**Comment by amoeba** [comment]
Just noting here that @nahf 	's PR #1303 was merged into `dev-2.10` today.
