### ISSUE TITLE
Index the EML Project funding

### ISSUE THREAD

**Issue by laurenwalker** [NCEAS/metacat#1256]
Add a `funding` field to the Solr index that contains the text from the EML Project `funding` element.

**Comment by amoeba** [comment]
I've got this change in with the rest of my EML 2.2.0 changes and this issue will close once those are merged into master.

**Comment by mbjones** [comment]
Excellent.  With EML 2.2, we have a bit more structure to the funding field, which now looks like this:

```xml
<award>
      <funderName>National Science Foundation</funderName>
      <funderIdentifier>https://doi.org/10.13039/00000001</funderIdentifier>
      <awardNumber>1546024</awardNumber>
      <title>Scientia Arctica: A Knowledge Archive for Discovery and Reproducible Science in the Arctic</title>
      <awardUrl>https://www.nsf.gov/awardsearch/showAward?AWD_ID=1546024</awardUrl>
</award>
```

and so I think we would want to be able to search and facet on the following:

* funderName
* funderIdentifier
* awardNumber

We might also want to be able to link using the `awardTitle` and `awardURL`, but maybe that happens in XSLT rather than SOLR.

Schema.org recently added new fields that correspond to these, so we should probably check for consistency in concept (although the field names differ a bit I think).

**Comment by amoeba** [comment]
Thanks! I filed a separate issue to discuss the indexing changes for the `AwardType` and I think copied your comments there faithfully: https://github.com/NCEAS/metacat/issues/1348.

Re:

> We might also want to be able to link using the awardTitle and awardURL, but maybe that happens in XSLT rather than SOLR.

That would generally happen in XSLT rather than Solr but I actually think it shouldn't happen in XSLT as XSLT 1.0 isn't quite powerful enough to sanitize HTML against XSS. There are some XML/HTML sanitizers out there the view service could use before sending the translated content to the client which I think is the way to go. We can linkify things that look like links using MetacatUI in an XSS-safe-ish way but then not all clients get the benefit. @csjx and I had a quick chat the other week about this. @mbjones do you think I should open another Issue to talk about this? The alternative would be not turn URLs into links until we come up with a solution.
