### ISSUE TITLE
500 (Internal Server Error) when non-ascii characters are not inserted

### ISSUE THREAD

**Issue by vchendrix** [NCEAS/metacat#1339]
Non-ASCII characters in JSON-LD meta data submission fails with a 500:
```
Error inserting or updating document: ess-dive-d853364f59854e1-20190322T230647892230 since 
<?xml version=\"1.0\"?>
<error>Invalid character data was found. This is most likely caused 
by stored data containing characters that are invalid for the character 
set the database was created in. The most common example of this 
is storing 8bit data in a SQL_ASCII database.
</error>
```
This should be handled with a 400 error.

**Comment by mbjones** [comment]
@vchendrix could you clarify the exact API method that was called to generate this error, and, if possible, provide a reproducible example? There is not enough information to evaluate whether a 4xx or 5xx series error is appropriate. Because it is likely a database configuration mismatch, a service failure may indeed be appropriate. 400 errors are client errors and should be fixable by the caller alone by fixing the request, whereas I suspect this will require a service reconfiguration by the admin. Let's discuss.

**Comment by taojing2002** [comment]
I chatted with @vchendrix and she said she only experienced this once.
