### ISSUE TITLE
Search page should link via dataset series ID 

### ISSUE THREAD

**Issue by FiannaOBrien** [NCEAS/metacat#1354]
**Suggestion**: When user selects a dataset from search page, the dataset page should have series ID in URL rather than PID. Many of our users don't know about the series ID or how wonderful a tool it is.

**Comment by laurenwalker** [comment]
Hi Fianna - This is already a feature of MetacatUI, but it's not displayed on your ESS-DIVE MetacatUI because I believe your MetacatUI theme overrides the `CitationView` and it's `render()` function. You would need to either stop overriding that function or merge back in the code from the main CitationView that displays the seriesId. 

As you can see on https://search.dataone.org, when you filter to the ESS-DIVE datasets, the seriesId is displayed.
