### ISSUE TITLE
Publishing dataset with prov loses all prov relationships

### ISSUE THREAD

**Issue by laurenwalker** [NCEAS/metacat#1366]
Related to #1363 

**Steps to reproduce:**
1. Create a new dataset
2. Add provenance relationships in MetacatUI and click Save
3. After saving, click Edit, and edit the metadata in MetacatUI (e.g. change the title and click Submit)
4. Click the "view dataset" link to view the dataset landing page
5. Click "Publish with DOI"
6. Notice that the publish call succeeds, the page is refreshed, but all the provenance relationships are missing.

This happened in production to this dataset: 
Before: https://knb.ecoinformatics.org/view/urn:uuid:66e76292-46f9-4e51-8d54-d30ab87f4ec7
After: https://knb.ecoinformatics.org/view/doi:10.5063/F1KP80GX

And on dev.nceas:
Before: https://dev.nceas.ucsb.edu/view/urn:uuid:1e85a8ac-98f3-418d-9bd1-133c31c65039
After: https://dev.nceas.ucsb.edu/view/doi:10.5072/FK2445RW5D

**Comment by gothub** [comment]
Regarding the refactor of metacat to parse all the DataONE ProvONE relationships, here some examples of current PROV and ProvONE and related terms and the namespace definitions:
```
dcterms  =  "http://purl.org/dc/terms/"
rdf = "http://www.w3.org/1999/02/22-rdf-syntax-ns#"
prov = "http://www.w3.org/ns/prov#"
provone = "http://purl.dataone.org/provone/2015/01/15/ontology#"

dcterms:identifier
dcterms:Agent
rdf:type
prov:qualifiedAssociation
prov:wasDerivedFrom
prov:wasInformedBy
prov:hadPlan
prov:used
prov:wasGeneratedBy
prov:Association          
prov:WasAssociatedWith 
prov:Agent                
provone:Program
provone:Execution
provone:Data
provone:User
```
This set of terms does not contain all possible ProvONE terms, but just the ones that are currently implemented in the R client and MetacatUI.

Compiling an exhaustive list of all potential PROV and ProvONE RDF relationships, and then querying a parsed resmap to determine which relationships to carry forward, seems to be an error prone method and precludes future relationships that may be added in the future.

One approach would be to retain any relationships that use the PROV and ProvONE and RDF namespaces.

**Comment by mbjones** [comment]
In general, I think our tools need to be careful to not lose data from ORE resource maps that they don't understand during updates.  I think in general it's better to retain a triple than to lose it.  There will likely be other vocabularies added to ORE docs in addition to PROV over time (that's why we chose RDF), and those should not be dropped.  When an update occurs, the tool will need to understand the semantics of each triple to know how to update it, but the old statement should still stand (using the original identifiers).  So if we don't understand the semantics, just keep the original triple.  Here's an example:

```
ex:A2 prov:wasDerivedFrom ex:B1
ex:A2 dct:title "A title"
ex:C ex:fooProperty ex:D
```
 Upon an update in which we create a new version `A3` of `A2`, we should have:

```
ex:A2 prov:wasDerivedFrom ex:B1
ex:A2 dct:title "A title"
ex:C ex:fooProperty ex:D
ex:A3 prov:wasRevisionOf ex:A2
```

We don't automatically know that A3 was derived from B1, but we do still know that A2 was derived from B1 -- that nugget did not change.  It would be nice to know if A3 was derived from B, but the tool can only add that if it knows it was the case. Similarly, the title might also be reasonably updated, but the tool can only do that if it understands the semantics.

 The update also didn't affect objects C or D at all, and so the random `ex:fooProperty` should be carried forward too and not be dropped, especially if C or D are in the package.

**Comment by laurenwalker** [comment]
In this particular case though, publishing the metadata with a DOI, I think we can make the assumption that any statements about the metadata object before publish are also true after publish. So couldn't we just replace all instances of the old metadata in the RDF with the new DOI?

I was reading the discussion on Slack yesterday and it was my understanding that @taojing2002 and @gothub were discussing a white-list of provenance relationships to retain during publish. If my understanding is correct, I think that's the wrong way to go here. I agree with Matt's statement that: 

> There will likely be other vocabularies added to ORE docs in addition to PROV over time (that's why we chose RDF), and those should not be dropped.

Instead of creating a white-list of ProvONE relationships to retain, we should keep ALL relationships intact unless they are related to the ORE aggregation. The way MetacatUI updates the RDF is it only updates the relationships that it understands and leaves everything else as-is. That way users can insert any statements into the RDF they want, regardless of whether our tools know about them.

**Comment by taojing2002** [comment]
Thanks @gothub @mbjones @laurenwalker @amoeba 
Yes, Metacat need only updates the relationships that it understands and leaves everything else as-is. In this case, we only need to update the `documents/documentedBy` relationship and add a new statement of the relationship of `prov:wasRevisionOf`.

Here is the current way how we generate the new resource map which will contains the new DOI:
We use a resource map parser from d1_java_libclient, which will return a map holding the `documents/documentedBy` relationship, to parse the original (old) resource map file. After we get the returned the map, we replace the old pid by the new DOI in the map. Then we build a new resource map base on the new map. Since the map only holds the `documents/documentedBy` informations , besides them, other relationships will be lost.

Here is the way I am thinking - instead of rebuilding a new resource map base on a structure map, we can use Jena to modify the resource map model which was built from the old resource map file, then serialize it:

- Create a new resource for the new DOI
- Query the model with the predicate of `documents/documentedBy` and replace the resource of the old pid by the resource of the DOI in those statments
- Add a new statement of the `prov:wasRevisionOf` relationship between the new DOI and the old pid

**Comment by gothub** [comment]
I provided the prov terms above as requested, but as mentioned on the related slack conversation I was not advising using as a white list, but instead was advocating retrieving and carrying forward all relationships from the resmap and modifying just those related to the metadata pid update.

**Comment by taojing2002** [comment]
Yeah, I was thinking to use a white list first. Thanks Peter for 
providing it. Now it seems this is not good idea.

**Comment by taojing2002** [comment]
Lauren and I tested my local server with the fixed code. It worked.
