### ISSUE TITLE
Stop creating records on the xml_node table when the Metacat instance doesn't support the xpath query engine

### ISSUE THREAD

**Issue by taojing2002** [NCEAS/metacat#1400]
If a Metacat instance doesn't support the path query engine (`dbquery.enabledEngines=solr`), Metacat currently doesn't generate any records on the `xml_index` and `xml_path_index` tables.  DataONE CNs have this behavior. This approach already decreases the database table size a lot since the xml_index table generally is the biggest table. 
However, i am thinking we can make Metacat doesn't generate the records on the xml_node either. This will also cause no records on the xml_node_revision either. Without records on those four tables (`xml_index`, `xml_path_index`, `xml_nodes` and `xml_node_revision`), the database size will be dramatic smaller. 
The xml_node and xml_revision tables are used for the `read` method on old Metacat APIs. We already replaced it by reading information from files on the disk. So there is no need for this purpose. The two tables also be used to build the path index. However, if the Metacat instance is set not to support the path query engine, there is no need either. I can't think of other usages of the two tables. 
Comments and suggestion are really appreciated.

**Comment by mbjones** [comment]
Insert speeds will also be faster.  I support this change.  Please review any other database tables that can be disabled when `dbquery.enabledEngines=solr`.  We discussed removing all of this infrastructure in that backwards incompatible Metacat 3.0, so refactoring it all so that it can be enabled/disabled in configuration is a good first step in being sure there aren't any odd side effects.

**Comment by taojing2002** [comment]
We will remove the table on 3.0.0.

**Comment by taojing2002** [comment]
Duplicate by 1365
