### ISSUE TITLE
support hierarchical packages in getPackage API

### ISSUE THREAD

**Issue by mbjones** [NCEAS/metacat#1438]
The current `getPackage` API downloads all package files in a flat folder within BagIt.  Modify the Metacat implementation to honor the new package format in PR https://github.com/DataONEorg/api-documentation/pull/4 in which files can be placed in a hierarchy using the `schema:atLocation` property.  This basically requires modifying the serialization to 1) create files in the correct paths within the BagIt `data` directory, and 2) modify manifest files to reflect these additional locations.

**Comment by ThomasThelen** [comment]
### To Do:
1. [ ] Finish up the README. This has gone through a few rounds of feedback, and I _think_ I'm on the last iteration (hoping to present on the April 30th dev call).
1. [ ] Figure out a way to keep the `PackageDownloader` class from knowing about the MNode class
1. [ ] File Efficiency: To do everything with streams, we need to fork the LoC BagIt library and write methods parallel to the current ones (but using streams instead of Java File). Since BagIt requires the checksums of files, and we want to stream the files to the user.... We need to write our own code that checksums the file as we stream it, adds the value to the manifest, and then serves the manifest files last. The idea was to tackle the input streams first, which will save a write to the disk (should get rid of half of the writes to disk). Doing both of these will be pushing my limits of Java and I'll need a lot of help with it.

### Known Bugs
1. Due to the number of different ways atLocation can be said, it should be located in the resource map with a SPARQL query rather than string matching.

**Comment by ThomasThelen** [comment]
Update: With the SpeedBagIt branch merged I'll begin merging the hierarchical feature branch with develop to get rid of the disk writes.

**Comment by ThomasThelen** [comment]
Note that we should add BagIt 1.0 to the format type list

**Comment by ThomasThelen** [comment]
Hierarchical packages wasn't shipped with the speedbagit refactor. The followup task was to refactor all of the hierarchical packages work I had previously done (which I had written using the original write-to-disk method) to work with speedbagit to eliminate the writes and to add support for multiple download formats. 

I have the hardest parts of that task done (refactoring _getPackage_ and ) and am left with refactoring the unit tests, more testing, and fixing any bugs that crop up. The things that need to be tested are the refactored V1 implementation and V2 edge cases + different science metadata formats.

I haven't had the chance to do the above so I have the code sitting on my machine; give me the weekend and I should be able to get in a PR for code review!

**Comment by ThomasThelen** [comment]
After the check_mk issues and reboot on probable-cattle, the VM ended up in an odd state where tomcat, solr, and Java are all missing. I put a little time into getting the metacat stack back up but haven't competed it yet; if there's a different deployment that I can test the feature on it would save a little time but this unexpected debugging and VM issue will stretch this out a little past Monday

**Comment by ThomasThelen** [comment]
This has been merged in #1562 and is now deployed on dev.nceas. I'll leave this open until it's deployed on production, but if anyone else wants to close it feel free to.
