### ISSUE TITLE
metacat-index gives incorrect `collectionQuery` solutions 

### ISSUE THREAD

**Issue by gothub** [NCEAS/metacat#1494]
@tao Please note the following:

In some cases, the "PortalSubProcessor" gives incorrect results.
Running tests against the collection/portals 1.1.0 examples shows incorrect results. Here are some sample documents from the [collection/portal repo](https://github.com/DataONEorg/collections-portals-schemas/tree/dev-1.1/docs/examples) with what should be (I think) the correct results:
```
1. example-portal-A.xml
-((isPartOf:urn\:uuid\:1a0fc71f-2d4b-404b-9cf5-aa82db18479c) OR text:(atlantic OR text:pacific))
AND (-obsoletedBy:* AND formatType:METADATA)

2. example-portal-B.xml
-((isPartOf:urn\:uuid\:1a0fc71f-2d4b-404b-9cf5-aa82db18479c) OR (-kingdom:Animalia))
AND (-obsoletedBy:* AND formatType:METADATA)

3. example-portal-C.xml
((isPartOf:urn\:uuid\:1a0fc71f-2d4b-404b-9cf5-aa82db18479c OR seriesId:S1_201628322590140) OR (identifier:urn\:uuid\:aa80a1a5-b1bc-4788-9ca6-76c77247593b AND keywordsText:polar) OR (id:urn\:uuid\:4852b15a-9c05-480b-b91d-fa34a59ce073)) AND (-obsoletedBy:* AND formatType:METADATA)

4. example-portal-D.xml
-((isPartOf:urn\:uuid\:1a0fc71f-2d4b-404b-9cf5-aa82db18479c OR seriesId:S1_201628322590140) OR (identifier:urn\:uuid\:aa80a1a5-b1bc-4788-9ca6-76c77247593b AND keywordsText:polar AND title:*remote*) OR (id:urn\:uuid\:4852b15a-9c05-480b-b91d-fa34a59ce073)) AND (-obsoletedBy:* AND formatType:METADATA)

5. example-portal-E.xml
(((isPartOf:urn\:uuid\:1a0fc71f-2d4b-404b-9cf5-aa82db18479c) OR ((((title:*flower* OR title:*leaf*) OR (abstract:*flower* OR abstract:*leaf*)) AND datePublished:[2018-01-01T00:00:00Z TO *]) AND -(keywordsText:vegetation OR authorGivenNameSort:William) AND (identifier:urn\:uuid\:1dbd8284-b388-4268-8bde-f53dca8710b2 OR identifier:urn\:uuid\:e68d6da6-9f68-42fd-8c85-5fbaa7325569 OR identifier:urn\:uuid\:71bad44a-0d9f-45fe-8966-ec63dd2f3357 OR identifier:urn\:uuid\:baa20036-dcc8-4828-95f9-bda380f7fc28) AND (documents:* OR -projectText:*))) AND (-obsoletedBy:* AND formatType:METADATA))
```

I think that the last solution might not be correct.

@robyngit could verify the query solutions I posted are correct for these documents?

**Comment by robyngit** [comment]
I purposefully built these example to include the tricky cases, so actually, MetacatUI gives different queries for all of these examples. From the `feature-rule-groups` branch:

```
1. example-portal-A.xml
((-(text:(atlantic OR pacific)) AND *:*) OR isPartOf:urn\:uuid\:1a0fc71f-2d4b-404b-9cf5-aa82db18479c)
AND (-obsoletedBy:* AND formatType:METADATA)

2. example-portal-B.xml
((-(-kingdom:Animalia AND *:*) AND *:*) OR isPartOf:urn\:uuid\:1a0fc71f-2d4b-404b-9cf5-aa82db18479c)
AND (-obsoletedBy:* AND formatType:METADATA)

3. example-portal-C.xml
((keywordsText:polar) OR (isPartOf:urn\:uuid\:1a0fc71f-2d4b-404b-9cf5-aa82db18479c OR id:urn\:uuid\:4852b15a-9c05-480b-b91d-fa34a59ce073 OR identifier:urn\:uuid\:aa80a1a5-b1bc-4788-9ca6-76c77247593b OR seriesId:S1_201628322590140))
AND (-obsoletedBy:* AND formatType:METADATA)

4. example-portal-D.xml
((-(((keywordsText:polar AND title:*remote*)) OR (id:urn\:uuid\:4852b15a-9c05-480b-b91d-fa34a59ce073 OR identifier:urn\:uuid\:aa80a1a5-b1bc-4788-9ca6-76c77247593b OR seriesId:S1_201628322590140)) AND *:*) OR isPartOf:urn\:uuid\:1a0fc71f-2d4b-404b-9cf5-aa82db18479c)
AND (-obsoletedBy:* AND formatType:METADATA)

5. example-portal-E.xml
((((((title:(*flower* OR *leaf*) OR abstract:(*flower* OR *leaf*)) AND datePublished:[2018-01-01T00:00:00Z TO 2021-12-31T23:59:59Z])) AND (-((keywordsText:vegetation OR authorGivenNameSort:William)) AND *:*) AND ((documents:* OR (-projectText:* AND *:*))))) OR (isPartOf:urn\:uuid\:1a0fc71f-2d4b-404b-9cf5-aa82db18479c OR identifier:(urn\:uuid\:1dbd8284-b388-4268-8bde-f53dca8710b2 OR urn\:uuid\:e68d6da6-9f68-42fd-8c85-5fbaa7325569 OR urn\:uuid\:71bad44a-0d9f-45fe-8966-ec63dd2f3357 OR urn\:uuid\:baa20036-dcc8-4828-95f9-bda380f7fc28)))
```

There are some cases that MetacatUI treats differently from how they are configured in in the portal/collection document, some of which seem to be followed by the "PortalSubProcessor", like always `OR`ing filters with the `id` field. Now that more solr fields are available, nested filter groups are possible, and the exclude field can be used for both filters and filter groups, dealing with the special cases is more complex than before. Here is a summary of how it works in MetacatUI:

## ID filters

Filters are considered "ID filters" if they contain at least one of the "ID fields". "ID fields" are the solr fields that are configured in MetacatUI's [AppModel.queryIdentifierFields](https://github.com/NCEAS/metacatui/blob/9b0bf0eebd019b6f0e671cb3e899c2e66a029951/src/js/models/AppModel.js#L1421-L1430). By default they include `id`, `identifier`, `seriesId`, and `isPartOf`. These filters are treated specially in MetacatUI, as described below.


## Query strings for filterGroups

The main structure of queries built from `<filterGroup>` or `<definition>` elements is: 

`( ( mainQuery ) OR idFilterQuery OR isPartOfQuery ) AND catalogQuery`

where:
- `idFilterQuery` is the query string built from any of the ID filters `OR`'ed together
- `isPartOfQuery` is the query string built from the filter with field set to `isPartOf`
- `mainQuery` is the query built from any non-ID and non-isPartOf filters, and
- `catalogQuery` is the `(-obsoletedBy:* AND formatType:METADATA)` suffix

The query must be built a differently for filter groups that have `<exclude>true</exclude>`. The structure for these "negative" query groups is:

`( ( -( mainQuery OR idFilterQuery ) AND *:* ) OR isPartOfQuery ) AND categoryQuery`

The differences with "negative" filter groups, are that:
1. We need to add the positive clause ` AND *:*` (See [this issue](https://github.com/NCEAS/metacatui/issues/1600) for a discussion on why this extra query fragment is needed), and
2. We never want to exclude the results of the `isPartOf` filter - it's there to eventually allow dataset owners to add their data to an existing portal that they do not own. 

## Building query fragments from filters

- If no `<fieldsOperator>` or `<operator>` is present, then default to `AND`, *unless* this is an ID filter, then default to `OR` for the `<operator>`.

- If the filter has `<exclude>true</exclude>`, then we append the positive clause ` AND *:*` to the resulting query string in most cases. 

Example:

```
<filter>
  <field>text</field>
  <value>whale</value>
  <exclude>true</exclude>
</filter>
```
would most often translate to:
`-text:whale AND *:*`

The extra clause is NOT added if there are other, positive filters that are `AND`'ed together with this filter. Example:

```
<filter>
  <field>text</field>
  <value>whale</value>
  <exclude>true</exclude>
</filter>
<filter>
  <field>title</field>
  <value>ocean</value>
</filter>
```
translates to:
`-text:whale AND title:ocean`

Note that if the subsequent filter is `OR`'ed to the negative filter, then the positive clause **is** required. In addition, if the next part of the query is an `OR` operator, then the negative query + positive clause should be wrapped in parentheses, e.g. `(-text:whale AND *:*)`. The parentheses are required because `-text:whale AND *:* OR field:value` does not give the same results as `(-text:whale AND *:*) OR field:value`.

**Comment by gothub** [comment]
@robyngit thx for the detailed description of how MetacatUI assembles the filter query, and for providing really helpful examples that use the new schema 1.1.0 features. 

The changes that have been made to the metacat-index algorithm that generates the `collectionQuery` field:
- use the same terminology for query components as MetacatUI (idFilter, isPartOfFilter, catalogQuery, etc.)
- use the same Solr mechanism required for negative queries (i.e. -term AND *:*)
- reduce the use of parentheses where possible, assure they are present when needed
- arrange the query terms to be in the same order as MetacatUI, i.e.
  - *( ( mainQuery ) OR idFilterQuery OR isPartOfQuery ) AND catalogQuery*

**Comment by robyngit** [comment]
That's great @gothub! Are you now getting the same collection query strings as MetacatUI for portal examples A to E ?

**Comment by gothub** [comment]
@robyngit the query results are the same for examples A to E, but the query strings are slightly different, as the metacat-index algorithm doesn't gather multiple values for a field - e.g. "(title:whale AND title:pacific)", not "title:(what AND pacific)", and sometimes parenthesis are included when not strictly necessary. BTW, I'd like to verify more results on test.arcticdata.io of MetacatUI vs metacat-index, and so should be able to push a PR tomorrow.

Here are the results of evaluating the queries on test.arcticdata.io:
```
example-portal-A.xml
metacatui
((-(text:(atlantic OR pacific)) AND *:*) OR isPartOf:urn\:uuid\:1a0fc71f-2d4b-404b-9cf5-aa82db18479c) AND (-obsoletedBy:* AND formatType:METADATA)
result count: 15023

metacat-index
((-((text:atlantic OR text:pacific)) AND *:* ) OR isPartOf:urn\:uuid\:1a0fc71f-2d4b-404b-9cf5-aa82db18479c) AND (-obsoletedBy:* AND formatType:METADATA)
result count: 15023

example-portal-B.xml
metacatui
((-(-kingdom:Animalia AND *:*) AND *:*) OR isPartOf:urn\:uuid\:1a0fc71f-2d4b-404b-9cf5-aa82db18479c) AND (-obsoletedBy:* AND formatType:METADATA)
result count: 3

metacat-index
((-(-(kingdom:Animalia) AND *:* ) AND *:* ) OR isPartOf:urn\:uuid\:1a0fc71f-2d4b-404b-9cf5-aa82db18479c) AND (-obsoletedBy:* AND formatType:METADATA)
result count: 3

example-portal-C.xml
metacatui
((keywordsText:polar) OR (isPartOf:urn\:uuid\:1a0fc71f-2d4b-404b-9cf5-aa82db18479c OR id:urn\:uuid\:4852b15a-9c05-480b-b91d-fa34a59ce073 OR identifier:urn\:uuid\:aa80a1a5-b1bc-4788-9ca6-76c77247593b OR seriesId:S1_201628322590140))
AND (-obsoletedBy:* AND formatType:METADATA)
result count: 154

metacat-index
((((keywordsText:polar)) OR id:urn\:uuid\:4852b15a-9c05-480b-b91d-fa34a59ce073 OR identifier:urn\:uuid\:aa80a1a5-b1bc-4788-9ca6-76c77247593b OR seriesId:S1_201628322590140) OR isPartOf:urn\:uuid\:1a0fc71f-2d4b-404b-9cf5-aa82db18479c) AND (-obsoletedBy:* AND formatType:METADATA)
result count: 154

example-portal-D.xml
metacatui:
((-(((keywordsText:polar AND title:*remote*)) OR (id:urn\:uuid\:4852b15a-9c05-480b-b91d-fa34a59ce073 OR identifier:urn\:uuid\:aa80a1a5-b1bc-4788-9ca6-76c77247593b OR seriesId:S1_201628322590140)) AND *:*) OR isPartOf:urn\:uuid\:1a0fc71f-2d4b-404b-9cf5-aa82db18479c)
AND (-obsoletedBy:* AND formatType:METADATA)
result count: 15542

metacat-index:
((-(((keywordsText:polar AND title:*remote*)) OR id:urn\:uuid\:4852b15a-9c05-480b-b91d-fa34a59ce073 OR identifier:urn\:uuid\:aa80a1a5-b1bc-4788-9ca6-76c77247593b OR seriesId:S1_201628322590140) AND *:* ) OR isPartOf:urn\:uuid\:1a0fc71f-2d4b-404b-9cf5-aa82db18479c) AND (-obsoletedBy:* AND formatType:METADATA)
result count: 15542

example-portal-E.xml
metacatui
((((((title:(*flower* OR *leaf*) OR abstract:(*flower* OR *leaf*)) AND datePublished:[2018-01-01T00:00:00Z TO 2021-12-31T23:59:59Z])) AND (-((keywordsText:vegetation OR authorGivenNameSort:William)) AND *:*) AND ((documents:* OR (-projectText:* AND *:*))))) OR (isPartOf:urn\:uuid\:1a0fc71f-2d4b-404b-9cf5-aa82db18479c OR identifier:(urn\:uuid\:1dbd8284-b388-4268-8bde-f53dca8710b2 OR urn\:uuid\:e68d6da6-9f68-42fd-8c85-5fbaa7325569 OR urn\:uuid\:71bad44a-0d9f-45fe-8966-ec63dd2f3357 OR urn\:uuid\:baa20036-dcc8-4828-95f9-bda380f7fc28))) AND (-obsoletedBy:* AND formatType:METADATA)

result count: 5488

metacat-index
(((((((title:*flower* OR title:*leaf*) OR (abstract:*flower* OR abstract:*leaf*)) AND datePublished:[2018-01-01T00:00:00Z TO *]) AND (-(keywordsText:vegetation OR authorGivenNameSort:William) AND *:* ) AND (documents:* OR (-(projectText:*) AND *:* )))) OR (identifier:urn\:uuid\:1dbd8284-b388-4268-8bde-f53dca8710b2 OR identifier:urn\:uuid\:e68d6da6-9f68-42fd-8c85-5fbaa7325569 OR identifier:urn\:uuid\:71bad44a-0d9f-45fe-8966-ec63dd2f3357 OR identifier:urn\:uuid\:baa20036-dcc8-4828-95f9-bda380f7fc28)) OR isPartOf:urn\:uuid\:1a0fc71f-2d4b-404b-9cf5-aa82db18479c) AND (-obsoletedBy:* AND formatType:METADATA)
result count: 5488
```
