### ISSUE TITLE
Extra event logged when MN.update was called

### ISSUE THREAD

**Issue by taojing2002** [NCEAS/metacat#1506]
When the mn.update method is called once, Metacat will create two events on the access_log. And data objects and metadata objects have different behaviors.
For a metadata object B, the new object updated an old one, the event log table looks like (with two update events):

| docid | event | date_logged     |
|------|-------|--------------|
|B        |update|2021-05-14 20:14:12.418|
|B        | UPDATE| 2021-05-14 20:14:12.49|

For a data object D, the new object updated an old one, the event log table looks like (with one create and one update events):
| docid | event | date_logged     |
|------|-------|--------------|
|D        |create|2021-05-14 21:49:24.17|
|D        | UPDATE| 2021-05-14 21:49:24.278|

So totally Metacat has four events for two MN.update calls. However, I think it should only have two events which have the value `update` (lower case) for object B and D:
| docid | event | date_logged     |
|------|-------|--------------|
|B        |update|2021-05-14 20:14:12.418|
|D        | update| 2021-05-14 21:49:24.278|

Do you agree with me?
Note: I confirmed that the event log method is called twice in the MN.update method.

**Comment by csjx** [comment]
Hi @taojing2002 - I agree that we should only be generating a single `create` event per object, and a single `update` event per object.  If only a metadata object is updated, only it should get the event and not the data object.  So I think you're correct above that there should be only two update events in this case, one for the metadata, and one for the data, since the bytes of both changed.
