### ISSUE TITLE
metacat hangs with excessive thread counts

### ISSUE THREAD

**Issue by mbjones** [NCEAS/metacat#1524]
Recently, we've been having Metacat 2.15 hang with excessive thread counts, and errors where Hazelcast gets out of memory errors. Jing traced one possible problem to an excessive number of LDAP threads being created. @taojing2002  reports:

```
@metamattj @chris I dumped the threads of arcticdata into a file.
5:45
4855 threads have the same stack trace:
5:46
stackTrace:
- java.net.SocketInputStream.socketRead0(java.io.FileDescriptor, byte[], int, int, int) @bci=0 (Compiled frame; information may be imprecise)
- java.net.SocketInputStream.socketRead(java.io.FileDescriptor, byte[], int, int, int) @bci=8, line=116 (Compiled frame)
- java.net.SocketInputStream.read(byte[], int, int, int) @bci=117, line=171 (Compiled frame)
- java.net.SocketInputStream.read(byte[], int, int) @bci=11, line=141 (Compiled frame)
- java.io.BufferedInputStream.fill() @bci=214, line=246 (Compiled frame)
- java.io.BufferedInputStream.read1(byte[], int, int) @bci=44, line=286 (Compiled frame)
- java.io.BufferedInputStream.read(byte[], int, int) @bci=49, line=345 (Compiled frame)
- com.sun.jndi.ldap.Connection.run() @bci=30, line=872 (Compiled frame)
- java.lang.Thread.run() @bci=11, line=748 (Compiled frame)
5:47
The root cause is com.sun.jndi.ldap.Connection.run().
5:48
I am not sure why we created some ldap connections.
```

So 4855 connection threads in a few hours. Looking into that, there are other examples of people having too many connections using StartTLS on LDAP (c.f., [StartTLS issues on Jenkins](https://issues.jenkins.io/browse/JENKINS-52374?page=com.atlassian.jira.plugin.system.issuetabpanels%3Aall-tabpanel)).  These were fixed by later versions of Java, and/or by not using StartTLS.

Another possibility is that we are simply not closing our LDAP Contexts all the time. While our code seems to call `Context.close()` in most of the methods in AuthLDAP.java, I do notice that the close is often done inside of a try/catch block or within a method that throws exceptions. So, when exceptions are generated, the `close()` call would be missed.   We should probably fix these by moving the close calls to a `finally` block to ensure they are called.  There are numerous places where this could happen in the code. Some examples:

 - [authenticateTLS()](https://github.com/NCEAS/metacat/blob/main/src/edu/ucsb/nceas/metacat/AuthLdap.java#L394), where we don't seem to close the `LdapContext ctx` at all
 - [getUsers()](https://github.com/NCEAS/metacat/blob/main/src/edu/ucsb/nceas/metacat/AuthLdap.java#L615), where `ctx.close()` is called in a try/catch and would be missed during a `NamingException`
 - [getAliasedDn()](https://github.com/NCEAS/metacat/blob/main/src/edu/ucsb/nceas/metacat/AuthLdap.java#L389), where `sctx.close()` would be skipped in the event of a `NamingException` or `IOException` because they are in the throws clause

Note that [NamingException](https://docs.oracle.com/javase/7/docs/api/javax/naming/NamingException.html) includes `NameNotFoundException` and many other exceptions that are common during normal operations and do not represent erroneous usage. So I would expect this situation to arise regularly.

**Comment by taojing2002** [comment]
I wrote a java client class which can read the system metadata of an object from test.arcticdata.io by three users: public, a token user and a certificate user. The program will go through every object in the server and read the system metadata by multiple threads. I ran this program on three machines in order to improve the intensity. 

Here are results in the dumping thread files:
1. Current code

| Ldap threads number\/Total threads number |
| --------------------- |
| 656\/760 |
| 890\/994 |
| 1453\/ 1577|

2. Modified code with closing the ldap context

| Ldap threads number\/Total threads number |
| --------------------- |
| 44\/126|
| 44\/147 |
| 382\/467|

3. Modified code with closing the ldap context plus commenting out the ldap search code in the D1ResourceHandler class:

| Ldap threads number\/Total threads number |
| --------------------- |
| 0\/105|
| 0\/122 |

So the things are getting better in this order 3>2>1.  In the scenario 3, the number of threads always keep about 100 -120.

**Comment by taojing2002** [comment]
The ticket related to add ldap search in the D1ResourceHandler class;
https://github.com/NCEAS/metacat/issues/1179

**Comment by taojing2002** [comment]
Add a cache mechanism on the AuthSession class. Now I ran the test again and the dumped thread result is:
|Ldap threads number/Total threads number|
|-----|
|0\/66|
|0\/77|
|0\/100|
So the cache mechanism seems work. We use the LRUMap class from Apache Common as the cache.
https://commons.apache.org/proper/commons-collections/apidocs/org/apache/commons/collections4/map/LRUMap.html
