### ISSUE TITLE
OSTI record reverts to SAVED on autoupdate after being SUBMITTED

### ISSUE THREAD

**Issue by FiannaOBrien** [NCEAS/metacat#1590]
On these two records, OSTI status was SUBMITTED, then changed to SAVED on autoupdate : [doi:10.15485/1865731](https://data.ess-dive.lbl.gov/view/doi:10.15485/1865731), [doi:10.15485/1865730](https://data.ess-dive.lbl.gov/view/doi:10.15485/1865730)

Relevant steps
Called Metacat API endpoint PUT `publishIdentifier`. 
OSTI record status switched to “SUBMITTED”
Updated package permissions using ESS-DIVE toolset on full data package (metadata & data files)
OSTI record status switched to “SAVED”

In working with [doi:10.15485/1865731](https://data.ess-dive.lbl.gov/view/doi:10.15485/1865731), I tried this process twice on production and saw the same behavior twice for the same package, where calling the `publishIdentified` endpoint switched the record to “SUBMITTED” and then updating the file permissions returned the record to “SAVED”.

This hasn’t happened with any other OSTI submissions.

Will update this ticket with any updates from OSTI support team.

**Comment by taojing2002** [comment]
This is a race issue when the client tries to update the datacite doc for the same object in different the threads. Metacat can't lock the remote resource in the DOI service and there is no way to fix the issue on the Metacat side. Fianna modified the client code and made sure the process be in a correct order. Then the issue is gone.
