### ISSUE TITLE
Metacat is deployable on Kubernetes, using a Helm Chart

### ISSUE THREAD

**Issue by artntek** [NCEAS/metacat#1623]
Built on top of the work for #1218 (**build a docker image for metacat**) - the goal is to be able to use helm to install or upgrade metacat on a k8s cluster. 

## Issues related to this epic:
* ~~#1635~~ 
* ~~#1662~~
* #1665

**Comment by artntek** [comment]
## ToDo Items

* defining site properties behavior for new vs. existing helm deployments
* some test failures to address
* Persistent Volume mounted at `/var/metacat` - working, but not poss to reconnect to same PV if Claim deleted when deployment deleted - so now creating claim only once, outside of deployment. Need to review with @mbjones 
* using secrets for passwords
* stop webapp running as root
* use helm subcharts & feature flags for dependencies (postgres, solr?)

**Comment by mbjones** [comment]
Hey @artntek nice to see your progress on the Postgres sub chart over in that branch. A small thought -- I've been thinking it would be better to not commit files, and particularly binary files, in the `charts` directory, with a similar rationale to not committing other build artifacts like jar files. Otherwise, our repo is going to start accumulating versions of the pg chart as we upgrade versions. Better to stick with just the Chart.yaml defining the dependency.

For context: https://stackoverflow.com/q/73599035

When the chart gets built with `helm dependency builds the dependency will be resolved, and when we package and release it it will be included in the artifact from `helm package`. Does that resonate with you?

**Comment by artntek** [comment]
Totally! I was in two minds about this, and ended up following the example I found in dataone_indexer (which has a solr binary checked in). I’d feel better leaving it out. What about the lock file - should that be checked in?

**Comment by mbjones** [comment]
Yeah, sorry about the indexer -- I've been meaning to change that one too. I'm not sure about the lockfile. It's a good question. I think it is probably not needed and will be generated anyways. Putting it in place would lock upgrades to a specific version for anyone who installed the chart, even if the chart label requested is fairly generic. If we have a really specific chart version listed in the dependencies, then the lock is probably not doing anything different.

Let's add `charts` to the .gitignore so it doesn't arise for others.

**Comment by artntek** [comment]
Removed binary and lock file in https://github.com/NCEAS/metacat/pull/1651

> Let's add `charts` to the .gitignore so it doesn't arise for others.

Done - https://github.com/NCEAS/metacat/pull/1652

**Comment by artntek** [comment]
# Exclusions for 3.0.0+

* Don't need `cgi-bin` setup
* Not supporting Morpho client
  * can omit `Context/useHttpOnly='false'` in `$TOMCAT/conf/context.xml`

**Comment by artntek** [comment]
closing this ticket - now tracking separately for: 
* MVP Release (3.0.0): #1665 
* Post-MVP: #1666
