### ISSUE TITLE
Make some DataONE APIs into transactions in Metacat

### ISSUE THREAD

**Issue by taojing2002** [NCEAS/metacat#1642]
Recently we got some reports that the Metacat instances only had partial records on objects. It is warning sign that uploading objects to Metacat is not a transaction. 

`Create`, `update`, and `delete` are the methods which should be transactions - they should either fully succeed or rollback properly. 

As we move Metacat instances to k8s , we should expect interruptions during those procedures more frequently.

So we need to design a system to do this job.

**Comment by mbjones** [comment]
@artntek @taojing2002 one way to determine if this will be a real issue on k8s deployments would be to develop a test for CRUD API operations that take some time and force a pod evictions at key points in the middle of what should be an atomic operation. For that to happen, we might need to test with a long-running operation, such as a large data upload. During that "transaction", we could then use the k8s [Eviction API](https://kubernetes.io/docs/concepts/scheduling-eviction/api-eviction/) to evict the metacat pod and make k8s spin it up on another node. This is what would happen if, for example, a hardware failure happens or if Nick cordons and drains a node for maintenance.  The example in the docs they give for the API call is:

```sh
curl -v -H 'Content-type: application/json' https://your-cluster-api-endpoint.example/api/v1/namespaces/default/pods/quux/eviction -d @eviction.json
```

We should be able to automate that in a test, albeit with some complications due to authentication against a k8s cluster -- its a complicated integration test. Maybe its sufficient for us to just run this run this test manually at first to gauge if there are even any issues here to be addressed.

**Comment by taojing2002** [comment]
In this [ticket](https://github.com/NCEAS/metacatui/issues/2235#issuecomment-1865232012): we found:

- the metacat code saves the metadata to Hazelcast (which, in turn, saves it to the database systemmetadata table), BEFORE checking the accessPolicy fields.
- the Chrome bug causes the accessPolicy section to be messed up https://github.com/NCEAS/metacatui/issues/2235#issuecomment-1862843645, which in turn causes metacat to throw an exception at this point (...InvalidSystemMetadata: The Permission shouldn't be null....), and fails to save the data object.
- Because the above steps are not part of a transaction, we now have the metadata saved, but not the data.
