### ISSUE TITLE
Bug: MetacatIndexServlet Fresh Startup Settings Error

### ISSUE THREAD

**Issue by artntek** [NCEAS/metacat#1698]
## [MetacatIndexServlet Fresh Startup Settings Error](metacat-index/src/main/java/edu/ucsb/nceas/metacat/index/MetacatIndexServlet.java)

On the first ever startup after a clean install, the value of `metacatSitePropertiesFilePath` is `null/metacat-site.properties`, resulting in an error (exception [thrown here](https://github.com/NCEAS/metacat/pull/1695/files#diff-5a6ce51b2ab11f2b7477046011aa2a90d2234dce6b3556350de680eebf7f30b1R72)).

When tomcat is restarted, however, this error goes away. (A simple restart fixes it; no other admin config steps required).

We should debug & fix this, otherwise k8s won't work. 

Stacktrace:

```console
==> /opt/homebrew/opt/tomcat@8/libexec/logs/catalina.out <==
metacat-index 20230920-14:15:47: [ERROR]: Could not find Metacat site properties at: null/metacat-site.properties [edu.ucsb.nceas.metacat.index.MetacatIndexServlet:init:71]

==> /opt/homebrew/opt/tomcat@8/libexec/logs/localhost.2023-09-20.log <==
20-Sep-2023 14:15:47.025 SEVERE [localhost-startStop-1] org.apache.catalina.core.StandardContext.loadOnStartup Servlet [metacat-index] in web application [/metacat-index] threw load() exception
 javax.servlet.ServletException: Could not find Metacat site properties at: null/metacat-site.properties
  at edu.ucsb.nceas.metacat.index.MetacatIndexServlet.init(MetacatIndexServlet.java:78)
  at org.apache.catalina.core.StandardWrapper.initServlet(StandardWrapper.java:1109)
  at org.apache.catalina.core.StandardWrapper.loadServlet(StandardWrapper.java:1061)
  at org.apache.catalina.core.StandardWrapper.load(StandardWrapper.java:958)
  at org.apache.catalina.core.StandardContext.loadOnStartup(StandardContext.java:4625)
  at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:4933)
  at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:171)
...etc
```

**Comment by taojing2002** [comment]
It turns out that the Metacat-index servlet  isn't able to read the property of `application.sitePropertiesDir` during the first startup. So it shows `null` there. The reason is the metacat-index.war file always expands earlier than metacat.war. So the metacat.properties file doesn't exist in the file system (it is still in the metacat.war file, not in the file system yet) when the metacat-index servlet tries to read the property of `application.sitePropertiesDir` from that file during the first startup. During the second tomcat startup, the metacat.war file was expanded and the metacat.properties exists in the file system, so everything works.

Matthew and I discussed the issue. Since in k8s, a script will expand both war files before the starting of Tomcat, it will be not an issue for it. So we don't need to do anything.
