### ISSUE TITLE
Don't use the hard code https in the property of index.d1node.baseURL

### ISSUE THREAD

**Issue by taojing2002** [NCEAS/metacat#1828]
Now we have hard code in this  property:
```
index.d1node.baseURL=https://${server.name}/${application.context}/d1/mn
```
So if the server doesn't use http, the index will break.

**Comment by doulikecookiedough** [comment]
For reference, after updating `index.d1node.baseURL`'s default value from `https` to `http` (ex. `http://${server.name}/${application.context}/d1/mn`) - I still experienced the connection refused error:

```metacat-index 20240317-09:08:15: [ERROR]: IndexWorker.indexOjbect - cannot index the task for identifier  urn:uuid:78c0a82c-e685-44a4-8909-df42c21c24b7 since class org.dataone.client.exception.ClientSideException: /Connect to localhost:80 [localhost/127.0.0.1, localhost/0:0:0:0:0:0:0:1] failed: Connection refused [org.dataone.cn.indexer.IndexWorker:indexOjbect:460]```

However, after hardcoding that property to `http://localhost:8080/metacat/d1/mn` appears to have resolved the issue of my test dataset not indexing. I can now view it in my local portal.

Note, my server port is set to 8080.

**Comment by mbjones** [comment]
I don't understand the problem here. This is in a properties file, right? Which is by definition **not** hardcoding -- it is where we set options that can be changed without recompiling the code. Can't the deployment just change their properties file?

Secondarily, did you mean that if the server doesn't use `https`, then the index will break? I think `https` is the correct default, and it should be discouraged/difficult for people to use plain http on an externally accessible service. The only place where plain http might make sense is within a private network (such as a Kubernetes cluster).

**Comment by artntek** [comment]
I think the root problem is that the property is set automatically, with a value that is incorrect when someone is running metacat without https enabled. This could be a developer, or worse, could be someone evaluating metacat. In either case, the value is not configurable via admin UI, so it's confusing when indexing fails and the installation doesn't work, causing significant time to be lost debugging and figuring out what went wrong.

The fix is super simple, and took less time than replying to this thread :-)  (PR #1829)

**Comment by taojing2002** [comment]
This property was a temporary solution when dataone-indexer can't only access the system metadata through the file system. Now 3.0.0 wouldn't use hash-store, so we need to polish it more.

**Comment by artntek** [comment]
As I'm looking at this now, I have a related question...

I believe `index.d1node.baseURL` is used by the dataone-indexer, ONLY when it is co-deployed with Metacat in the same Tomcat container (true or false, @taojing2002?). 

If so, wouldn't it be better to set it to the http `localhost` URL, instead of the external one? This would be faster, more secure, and wouldn't need the overhead of an ssl handshake.

**Comment by taojing2002** [comment]
@artntek Yes, it is used by dataone-indexer. Now it was for cn only (it is part of cn-indexer). But we expand the usage, so I don't think we can guarantee they are in the same Tomcat container.

**Comment by taojing2002** [comment]
@artntek I copied the comment from the PR for the next steps:

Do we really need this property? I think it can be replaced by dataone.mn.baseURL after I thought more. But this need some code change in dataone-index. Since the correctness of this property is important, it will be good to check the connection of the url. If the connection of the internal server fails ( I know someone likes to disable 8080 in Tomcat), we will try the external url. If both fail, we will ask user to check the settings. What do you think?

**Comment by artntek** [comment]
Jing and I discussed this. Conclusions:

1. merge the current PR (#1829), since it's an incremental improvement
2. New PR: In the `dataone-indexer` codebase, rename the property `index.d1node.baseURL` to `dataone.mn.baseURL` (i.e. so it references the existing property, instead of introducing a new one with the same value). 
    * (The `dataone.mn.baseURL` property is used only by the dataone indexer and the cn indexer, and not by metacat itself.)
3. New PR: Change [this part of `src/edu/ucsb/nceas/metacat/admin/PropertiesAdmin.java`](https://github.com/NCEAS/metacat/pull/1829/files#diff-7bf3768e57e2fba771f328a7d0c6d08221a194d642d08e7fda0e145f0147b63bR211) to do the following, in this order:
    1. Check to see if the indexer is co-deployed (is this possible before config??)
    2. Check if it can access the metacat d1 API on localhost:`server.internalPort`. If so, set `dataone.mn.baseURL` to point to localhost
    3. Check if it can access the metacat d1 API on the external server:pot that the code currently sets automatically. If so, set `dataone.mn.baseURL` to point to that instead
    4. If neither is accessible, throw a runtime exception to inform the operator, since this is a critical problem.
    5. (does some of this belong in `src/edu/ucsb/nceas/metacat/startup/StartupRequirementsChecker.java`...???)

**Comment by artntek** [comment]
https://github.com/DataONEorg/dataone-indexer/pull/68
