### ISSUE TITLE
Allowed submitters list fails with ORCIDs

### ISSUE THREAD

**Issue by csjx** [NCEAS/metacat#2]
As pointed out by @vchendrix in the ESS-DIVE project, adding an ORCID identifier to the `auth.allowedSubmitters` list in Metacat will fail to allow an `MN.create()` call by a submitter with that ORCID in the `Subject` of the authentication token. This is likely the case in the other lists like 
`auth.administrators` too.
At first glance, it seems like the following code in `edu.ucsb.nceas.metacat.util.AuthUtil.populateAllowedSubmitters()`:
```java
allowedSubmitters = StringUtil.toVector(allowedSubmitterString, ':');
```
is splitting the string on the `:` in the ORCID (like `http://orcid.org/xxxx-xxxx-xxxx-xxxx`)

So, we need to be able to handle subjects that include the delimiter character.  Attempting to wrap the ORCID in quote characters of course didn't work because the quotes a treated as raw characters.  So, we need to use a means of escaping the colon character when serializing or deserializing the string to and from the property list so the `Subject` strings are parsed correctly.

**Comment by vchendrix** [comment]
@csjx I am not sure if this is the appropriate place but this is also a problem with group names (e.g `CN=ess-dive-admins,DC=dataone,DC=org`)

**Comment by csjx** [comment]
Hey Val - yup - I wrote that up in #3 😄

**Comment by taojing2002** [comment]
We can use backslash characters to escape the colon character. So the arcid id should look like:
http\://orcid.org/xxxx-xxxx-xxxx-xxxx in that property. 

I searched online and found we could use regular expression to skip the escaped colon during splitting the string. The regex should look like:

regex = "(?<!\\\\)" + Pattern.quote(delim);

After get the orid id, we may replace the "\:" by ":".  Finally we get the correct subject.

It is not necessary to use backlash character as the escape character. However, since java uses it, it will better to be consistent.

**Comment by csjx** [comment]
After speaking with @taojing2002 about this, we decided to get the Metacat-side code to parse the `auth.allowedSubmitters` list correctly, and require the MN operator to manually escape colons. This is the fastest fix for ESS-DIVE, since they manually configure `metacat.properties` via their docker image anyway.  We will then fix the admin interface to automatically escape colons in a later bugfix release. See #29.
